PATH_POPUP_SKILINFO = "tui/tui_popup_skilinfo.xml"

Tag_popup_skilinfo = { 
PANEL_SKILL_INFO = 1 ,
IMG9_SKILL_POPUP_BG = 2 ,
LAB_POPUP_SKILL_NAME = 3 ,
LAB_SKILL_DESCRIPTION = 4 ,
LAB_SKILL_DESCRIPTION_NUM = 5 ,
LAB_POPUP_SKILL_NAME2 = 6 ,
LAB_SKILL_DESCRIPTION2 = 7 ,
LAB_SKILL_DESCRIPTION_NUM2 = 8 } 

