PATH_POPUP_REGISTER = "tui/tui_popup_register.xml"

Tag_popup_register = { 
PANEL_POPUP_REGISTER = 1 ,
IMG_DECORATE2 = 2 ,
IMG_POPUP_2 = 3 ,
LAB_ACCOUNT2 = 4 ,
LAB_PASSWORD2 = 5 ,
EDIT_ACCOUNT2 = 6 ,
EDIT_PASSWORD2 = 7 ,
LAB_SURE_PASSWORD = 8 ,
EDIT_SURE_PASSWORD = 9 ,
BTN_REGISTER2 = 10 ,
BTN_RETURN_LOGIN = 11 ,
LAB_ENSURE_LOGIN = 12 ,
IMG_PIKAQIU2 = 13 ,
LAB_RETURN_LOGIN = 14 } 

