PATH_UI_EXPLORE = "tui/tui_ui_explore.xml"

Tag_ui_explore = { 
PANEL_EXPLORE = 1 ,
IMG_EXPLORE__MAP = 2 ,
IMG_WORD_BG1 = 3 ,
LAB_PVE1 = 4 ,
IMG_WORD_BG3 = 5 ,
LAB_PVE2 = 6 ,
LAYOUT_CLOUD1 = 7 ,
LAYOUT_CLOUD2 = 9 ,
LAYOUT_EXPLORE_TOP = 11 ,
IMG_TOP_PYRAMID_BG = 12 ,
IMG_EXPLORE_TITLE = 13 ,
LAYOUT_EXIT_EXPLORE = 14 ,
LAYOUT_ACTIVITY2 = 16 ,
LAYOUT_ACTIVITY3 = 18 ,
LAYOUT_ACTIVITY1 = 20 ,
IMG_WORD_BG2 = 22 ,
LAB_PVE3 = 23 ,
IMG_WORD_BG5 = 24 ,
LAB_RETURNMAIN = 25 ,
LAYOUT_SHOP = 26 ,
IMG_WORD_BG4 = 28 ,
LAB_SHOP = 29 ,
LAYOUT_MIAN = 30 ,
LAYOUT_BIRD = 32 } 

