PATH_POPUP_ACTIVITY1_REWARD = "tui/tui_popup_activity1_reward.xml"

Tag_popup_activity1_reward = { 
PANEL_TURNTABLE_REWARD = 1 ,
IMG9_TURN_REWARD_BG3 = 2 ,
IMG9_TURN_REWARD_BG2 = 3 ,
IMG9_TURN_REWARD_BG1 = 4 ,
LAB_TURNTABLE_REWARD_TITLE = 5 ,
LAYOUT_TURN_ITEM = 6 ,
LAB_TURN_ITEM_NUM = 8 ,
BTN_TURN_CLOSE = 9 ,
LAB_TURN_CLOSE = 10 ,
LAB_TURNTABLE_REWARD_SCORE = 11 ,
LAB_TURN_SCORE = 12 } 

