PATH_POPUP_PYRAMID_REWARD = "tui/tui_popup_pyramid_reward.xml"

Tag_popup_pyramid_reward = { 
PANEL_PYRAMID_REWARDS = 1 ,
IMG9_POPUP_BG1 = 2 ,
IMG9_POPUP1 = 3 ,
LAB_REWARDS_BADGET = 4 ,
LAB_REWARDS_GOLD = 5 ,
IMG_REWARDS_GOLD = 6 ,
GV_REWARDS = 7 ,
BTN_CLOSE_REWARDS = 8 ,
IMG_REWARDS_BADGET = 9 ,
CELL_REWARD = 10 ,
LAYOUT_REWARD = 11 ,
LAYOUT_ITEM = 12 ,
LAB_ITEM_NUM = 14 } 

