PATH_UI_DUNGEON = "tui/tui_ui_dungeon.xml"

Tag_ui_dungeon = { 
PANEL_DUNGEON = 1 ,
IMG_CHAPTER_BG_MAP = 3 ,
LAYOUT_TOP = 4 ,
IMG_TITLE_CHAPTER = 5 ,
IMG_CHALLENGE_TITLE = 6 ,
LAYOUT_PVP1 = 7 ,
LAYOUT_PVP2 = 9 ,
LAYOUT_SHOP = 11 ,
LAYOUT_PVPTOUCH = 13 ,
LAYOUT_DUNGON = 15 ,
IMG_DUNGON_BOTTOM = 16 ,
BTN_RETURN = 17 ,
LAB_RETURN = 18 ,
IMG_WORD_BG2 = 19 ,
IMG_WORD_BG3 = 20 ,
LAYOUT_PVP2TOUCH = 21 ,
IMG_WORD_BG1 = 23 ,
LAB_PVP1 = 24 ,
LAB_SHOP = 25 ,
LAB_PVP2 = 26 } 

