PATH_POPUP_SETTING = "tui/tui_popup_setting.xml"

Tag_popup_setting = { 
PANEL_POPUP_SETTING = 1 ,
IMG9_POPUP_BG = 2 ,
LAYOUT_MUSIC = 3 ,
IMG_MUSIC_NORMAL = 4 ,
IMG_MUSIC_SELECT = 5 ,
LAYOUT_EFFECT = 6 ,
IMG_EFFECT_NORMAL = 7 ,
IMG_EFFECT_SELECT = 8 ,
BTN_COMMON = 9 ,
LAB_GET = 10 ,
EDIT_WORD = 11 ,
IMG9_POPUP = 12 ,
IMG_TITLE_BG1 = 13 ,
IMG_TITLE_BG2 = 14 ,
IMG_SETTING_TITLE = 15 ,
BTN_CLOSE = 16 ,
BTN_CONNECT = 17 ,
LAB_CONNECT = 18 ,
BTN_RETURNLOGIN = 19 ,
LAB_RETURN = 20 } 

