PATH_UI_ASSETS_UPDATER = "tui/tui_ui_assets_updater.xml"

Tag_ui_assets_updater = { 
PANEL_ASSETS_UPDATER = 1 ,
PROG_ASSETS_UPDATER = 2 ,
LAYOUT_SWORD_ANIM = 3 ,
IMG_ASSETS_UPDATER_SWORD = 4 ,
ANIM_ASSETS_UPDATER_PROG = 5 ,
LAB_UPDATE_PROGRESS = 6 ,
LAB_UPDATE_PROGRESS_PERCENT = 7 } 

