PATH_POPUP_BAG_SELLITEM = "tui/tui_popup_bag_sellitem.xml"

Tag_popup_bag_sellitem = { 
PANEL_POPUP_SELLITEM = 1 ,
IMG9_BG_DOWN = 2 ,
IMG9_BG_UP = 3 ,
LAYOUT_ITEM_SELLITEM = 4 ,
LAB_ITEMNAME_SELLITEM = 6 ,
LAB_ITEMNUM_SELLITEM = 7 ,
LAB_MULT = 8 ,
LAB_SELLNUM = 9 ,
LAB_GOTGOLD = 10 ,
IMG_GOLD_SELL = 11 ,
LAB_GOLDNUM = 12 ,
BTN_MAXNUM = 13 ,
BTN_SELL_CANCEL = 14 ,
BTN_SELL = 15 ,
LAB_CANCEL = 16 ,
LAB_SELLITEM = 17 ,
LAB_MAX_NUM = 18 ,
IMG_NUM_MIDDLE = 19 ,
BTN_NUM2 = 20 ,
BTN_NUM1 = 21 ,
IMG9_POPUP_SELLITEM = 22 ,
LAB_SELL_NUM = 23 } 

