PATH_POPUP_ITEM_DROP = "tui/tui_popup_item_drop.xml"

Tag_popup_item_drop = { 
PANEL_ITEM_DROP = 1 ,
IMG9_POPUP_BG33 = 2 ,
LIST_STAGE = 3 ,
LAYOUT_DROP = 20 ,
IMG_WOOD_UP_BG1 = 9 ,
LAYOUT_ITEM_PORTRAIT = 10 ,
LAB_ITEM_NAME = 13 ,
LAB_OWN = 14 ,
LAB_ITEM_OWN_NUM = 15 ,
LAB_ITEM_ALL_NUM = 16 ,
IMG9_POPUP33 = 17 ,
BTN_CLOSE_DROP = 18 ,
CELL_DROP = 19 ,
IMG_DROP_STAGE_BG = 21 ,
LAYOUT_STAGE_PORTRAIT = 22 ,
LAB_STAGE_NUM = 25 ,
LAB_STAGE_NAME = 26 ,
LAB_STAGE_TYPE = 27 ,
LAB_YIKAIQI = 28 ,
IMG_YIKAIQI = 29 ,
IMG_WEIKAIQI = 30 ,
IMG_BORDER_DROP = 31 } 

