PATH_POPUP_ANNOUNCE = "tui/tui_popup_announce.xml"

Tag_popup_announce = { 
PANEL_ANNOUNCE = 1 ,
IMG9_POPUP_BG = 2 ,
EXPLIST_ACHIEVEMENT = 3 ,
LAYOUT_ACHIEVEMENT_CONTENT = 5 ,
LAYOUT_EXPLIST = 6 ,
IMG9_DISPLAY_BG = 8 ,
LAB_ANNOUNCE_CONTENT = 9 ,
IMG_CONTENT_BG = 10 ,
LAB_TITLE = 11 ,
IMG_ARROW = 12 ,
LAB_NUM = 13 ,
IMG_WOOD_BG1 = 15 ,
IMG_WOOD_DOWN_BG1 = 16 ,
IMG_WOOD_DOWN_BG2 = 17 ,
IMG9_POPUP = 18 ,
IMG_TITLE1 = 19 ,
IMG_TITLE2 = 20 ,
IMG_ANNOUNCE_TITLE = 21 ,
BTN_CLOSE_ANNOUNCE = 22 ,
LAB_SURE = 23 } 

