PATH_POPUP_DAILY = "tui/tui_popup_daily.xml"

Tag_popup_daily = { 
PANEL_POPUP_DAILY = 1 ,
IMG9_POPUP_BG = 3 ,
LIST_DAILY = 4 ,
LAYOUT_DAILY = 6 ,
IMG_DAILY_CONTENT = 8 ,
LAB_DAILYTITLE = 9 ,
LAB_DAILY_DESC = 10 ,
LAB_DAILY_REWARD = 11 ,
IMG_TEAMEXP = 12 ,
LAB_TEAMEXP_MULT = 13 ,
LAB_DIAMOND_MULT = 14 ,
LAYOUT_DAILYPET = 15 ,
BTN_GO = 17 ,
LAB_GO = 18 ,
IMG_DAILY_BORDER = 19 ,
LAB_FINISH_PROG = 20 ,
IMG_DIAMOND = 21 ,
IMG_WOOD_BG1 = 23 ,
IMG9_POPUP = 24 ,
IMG_TITLE_DIALY1 = 25 ,
IMG_TITLE_DIALY2 = 26 ,
IMG_DAILY_TITLE = 27 ,
BTN_CLOSE_DIALY = 28 } 

