PATH_POPUP_END = "tui/tui_popup_end.xml"

Tag_popup_end = { 
PANEL_END = 1 ,
IMG9_END_REWARD_BG3 = 2 ,
IMG9_END_REWARD_BG2 = 3 ,
IMG9_END_REWARD_BG1 = 4 ,
LAB_END_SCORE = 5 ,
LAB_REWARD_NAME = 6 ,
LAB_JIANGLI = 7 ,
LAB_END_REWARD_NUM = 8 ,
LAB_END_SCORE_NUM = 9 ,
LAYOUT_REWARD_ITEM = 10 ,
LAB_REWARD_ITEM_NUM = 12 ,
BTN_ACTIVITY_END = 13 ,
LAB_ACTIVITY_END = 14 ,
LAB_REWARD_X2 = 15 } 

