PATH_POPUP_ACHIEVEMENT_CONTENT = "tui/tui_popup_achievement_content.xml"

Tag_popup_achievement_content = { 
PANEL_ACHIEVEMENT_CONTENT = 1 ,
IMG9_GET_REWARD_BG2 = 2 ,
IMG9_GET_REWARD_BG1 = 3 ,
IMG_CONGRATULATION = 4 ,
IMG_REWARD1 = 5 ,
LAB_REWARD_NUM1 = 6 ,
IMG_REWARD2 = 7 ,
LAB_REWARD_NUM2 = 8 ,
LAB_REWARD_NUM3 = 9 ,
IMG_REWARD3 = 10 ,
BTN_FUNCTION = 11 ,
LAB_GETITEM = 12 ,
LAYOUT_ITEM_REWARD1 = 13 ,
LAYOUT_ITEM_REWARD2 = 15 ,
LAYOUT_ITEM_REWARD3 = 17 ,
LAYOUT_ITEM_REWARD4 = 19 ,
IMG9_POPUP2 = 21 ,
LAB_ITEM_NUM1 = 22 ,
LAB_ITEM_NUM3 = 23 ,
LAB_ITEM_NUM4 = 24 ,
LAB_ITEM_NUM2 = 25 } 

