PATH_POPUP_NEW_PET = "tui/tui_popup_new_pet.xml"

Tag_popup_new_pet = { 
PANEL_POPUP_NEW_PET = 1 ,
IMG_NEWPET_BG = 2 ,
IMG_NEWPET_CIRCLE = 3 ,
LAYOUT_PET_BAGIMG = 4 ,
LAYOUT_NEWPET = 6 ,
IMG_NEWPET_TITLE = 8 ,
IMG_NEWPET_WORD = 9 ,
LAB_NEWPET_NAME = 10 ,
BTN_CLOSE_NEW_PET = 11 ,
LAB_CLOSE_NEW_PET = 12 } 

