PATH_UI_PYRAMID = "tui/tui_ui_pyramid.xml"

Tag_ui_pyramid = { 
PANEL_PYRAMID = 1 ,
LAB_CONTINUE_CHALLENGE = 2 ,
IMG_PYRAMID_BG = 3 ,
LAYOUT_BUTTOM = 4 ,
IMG_BUTTOM = 5 ,
LAB_REMAIN = 6 ,
LAB_REMAIN_NUM = 7 ,
BTN_PYRAMID_BACK = 8 ,
BTN_PYRAMID_RESET = 9 ,
LAB_PYRAMID_BACK = 10 ,
LAB_PYRAMID_RESET = 11 ,
LAYOUT_TOP = 12 ,
IMG_TITLE_PYRAMID_BG = 13 ,
IMG_PYRAMID_TITLE = 14 ,
BTN_RANK = 15 ,
BTN_CONTINUE_CHALLENGE = 16 ,
LAB_START_LAYER_NUM = 17 ,
BTN_GETREWARD = 18 } 

