PATH_POPUP_TREASURE_CHEST = "tui/tui_popup_treasure_chest.xml"

Tag_popup_treasure_chest = { 
PANEL_TREASURE_CHEST = 1 ,
IMG9_CHEST_BG4 = 2 ,
IMG9_CHEST_BG2 = 3 ,
IMG9_CHEST_BG = 4 ,
SCROL_REWARDS = 5 ,
BTN_CHEST_LEFTARROW = 7 ,
BTN_CHEST_RIGHTARROW = 8 ,
BTN_CLOSE_CHEST = 9 ,
IMG_GET = 10 ,
LAB_CLOSE_CHEST = 11 ,
CELL_CHEST_ITEM = 12 ,
LAYOUT_CHEST_ITEM = 13 ,
LAB_ITEM_NAME = 15 } 

