PATH_POPUP_PETINFO = "tui/tui_popup_petinfo.xml"

Tag_popup_petinfo = { 
PANEL_POPUP_PETINFO = 1 ,
IMG_PETINFO_BG = 2 ,
LAYOUT_PET_IMG = 3 ,
LAB_PETINFO_DESC = 5 ,
LAYOUT_PETINFO_1 = 6 ,
BTN_CLOSE = 8 ,
LAB_PETINFO = 9 ,
LAYOUT_PETINFO_2 = 10 ,
LAYOUT_PETINFO_3 = 12 ,
IMG_PET_ISCOLLECT = 14 } 

