PATH_POPUP_RECOVER_ENERGY = "tui/tui_popup_recover_energy.xml"

Tag_popup_recover_energy = { 
PANEL_RECOVER_ENERGY = 1 ,
LAYOUT_ENERGY_SPINE = 2 ,
LAYOUT_EAT = 4 ,
IMG_WOOD_UP_BG5 = 6 ,
IMG_WOOD_UP_BG6 = 7 ,
IMG9_RECOVER_BG1 = 8 ,
IMG_RECOVER_TITLE1 = 9 ,
IMG_RECOVER_TITLE2 = 10 ,
IMG_RECOVER_TITLE = 11 ,
BTN_RECOVER_CLOSE = 12 ,
IMG_TALK_BG = 13 ,
LAB_TALK = 14 } 

