PATH_POPUP_RANK_ARENA_CONTENT = "tui/tui_popup_rank_arena_content.xml"

Tag_popup_rank_arena_content = { 
PANEL_POPUP_POWER_RANKCONTENT = 1 ,
IMG9_POPUP_BG_3 = 2 ,
IMG9_POPUP_BG_2 = 3 ,
IMG9_POPUP_2 = 4 ,
LAB_XXXCC = 5 ,
LAB_ASSOCIATION = 6 ,
BTN_POWER_CLOSE = 7 ,
LAYOUT_PLAYER_2 = 8 ,
IMG_ITEM_FRAME_2 = 10 ,
IMG_NAME_BG_2 = 11 ,
IMG_LEVEL_POPUP = 12 ,
LAB_LEVEL_2 = 13 ,
LAB_POWER_PLAYER_NAME1 = 14 } 

