PATH_POPUP_RANK_PROMOTE = "tui/tui_popup_rank_promote.xml"

Tag_popup_rank_promote = { 
PANEL_RANK_PROMOTE = 1 ,
IMG9_POPUP_BG11 = 2 ,
IMG9_RANK_PROMOTE_BG = 3 ,
IMG_RANK_GROW_INFO_BG = 4 ,
IMG_RANK_CHANGE_BG = 5 ,
LAB_NEW_RANK = 6 ,
IMG_RANK_ARROW = 7 ,
LAB_COMMON_ATTACK_RANK = 8 ,
LAB_LIFE_RANK = 9 ,
LAB_LIFE_RANK_NUM = 10 ,
LAB_COMMON_ATTACK_RANK_NUM = 11 ,
LAB_RANK2 = 12 ,
IMG_PET_BASE = 13 ,
LAYOUT_PET_UPRANK = 14 ,
LAB_OLD_RANK = 17 ,
LAB_RANK1 = 18 ,
IMG_RANK_GROW_TITLE_BG1 = 19 ,
IMG_RANK_GROW_TITLE_BG2 = 20 ,
IMG_RANK_PROMOTE = 21 ,
BTN_RANK_GROW_CLOSE = 22 } 

