PATH_POPUP_PVP_VICTORY = "tui/tui_popup_pvp_victory.xml"

Tag_popup_pvp_victory = { 
PANEL_PVP_VICTORY = 1 ,
LAYOUT_VICTORY = 2 ,
IMG9_WIN_BG = 3 ,
IMG_WOOD_BG22 = 4 ,
IMG_WOOD_BG21 = 5 ,
BTN_SURE = 6 ,
LAB_SURE = 7 ,
IMG_WOOD_BG11 = 8 ,
IMG_WOOD_BG12 = 9 ,
IMG9_POPUP_VICTORY_BG = 10 ,
LAB_WIN_TIPS1 = 11 ,
LAB_RANK_NUM = 12 ,
LAB_FAME_NUM = 13 ,
LAB_DIAMOND_NUM = 14 ,
LAYOUT_REWARD1 = 15 ,
LAYOUT_REWARD2 = 17 ,
LAYOUT_REWARD3 = 19 ,
LAYOUT_WIN = 21 } 

