PATH_POPUP_BATTLE_DEFEAT = "tui/tui_popup_battle_defeat.xml"

Tag_popup_battle_defeat = { 
PANEL_POPUP_BATTLE_DEFEAT = 1 ,
IMG9_POPUP_CONTENT_DEFEAT = 2 ,
LAYOUT_WOOD_DOWN2 = 3 ,
IMG_WOOD_DOWN1 = 4 ,
IMG_WOOD_DOWN2 = 5 ,
LAYOUT_WOOD_UP2 = 6 ,
IMG_WOOD3 = 7 ,
IMG_WOOD4 = 8 ,
IMG9_POPUP_DEFEAT_BG = 9 ,
LAYOUT_LOSE = 10 ,
LAYOUT_TRAIN = 12 ,
BTN_TRAIN = 13 ,
IMG_TRAIN = 14 ,
LAYOUT_PET_TRAIN = 15 ,
LAYOUT_SKILL = 17 ,
BTN_SKILL = 18 ,
IMG_SKILL = 19 ,
LAYOUT_PET_SKILL = 20 ,
BTN_CLOSE_DEFEAT = 22 ,
BTN_NEXT_DEFEAT = 23 ,
BTN_AGAIN_DEFEAT = 24 } 

