PATH_POPUP_ACTIVITY1_ENCOUNTER = "tui/tui_popup_activity1_encounter.xml"

Tag_popup_activity1_encounter = { 
PANEL_POPUP_ACTIVITY1_ENCOUNTER = 1 ,
IMG9_ENCOUNTER_BG3 = 2 ,
BTN_SUPERBOSS = 3 ,
BTN_BOSS = 4 ,
BTN_MIDBOSS = 5 ,
BTN_ESCAPE = 6 ,
IMG9_ENCOUNTER_BG2 = 7 ,
LAB_CHOSE = 8 ,
IMG_SCORE_BG1 = 9 ,
IMG_SCORE_BG2 = 10 ,
IMG_SCORE_BG3 = 11 ,
IMG_SCORE_BG4 = 12 ,
LAB_DEFEN1 = 13 ,
LAB_DEFEN2 = 14 ,
LAB_DEFEN3 = 15 ,
LAB_DEFEN4 = 16 ,
LAB_ENEMY_TIP1 = 17 ,
LAB_ENEMY_TIP2 = 20 ,
IMG9_POPUP2 = 21 ,
IMG_TITLE_ENCOUNTER1 = 22 ,
IMG_TITLE_ENCOUNTER2 = 23 ,
IMG_LOOK_ENEMY = 24 } 

