PATH_POPUP_REGISTRATION = "tui/tui_popup_registration.xml"

Tag_popup_registration = { 
PANEL_POPUP_DAILYATTENDANCE = 1 ,
IMG9_GRAY_REGISTRATION = 2 ,
IMG9_POPUP_BG = 3 ,
IMG_POPUP_TITLE = 4 ,
LAB_REGISTRATION_3 = 5 ,
LAB_REGISTRATION_NUM = 6 ,
LAB_REGISTRATION_5 = 7 ,
LAB_REGISTRATION_2 = 8 ,
LAB_REGISTRATION_1 = 9 ,
GV_REGISTRATION = 10 ,
BTN_CLOSE = 11 ,
CELL_REGISTRATION = 12 ,
IMG_REGISTRATION_RECT = 13 ,
IMG_REGISTRATION_PROP = 14 ,
IMG_VIPDOUBLE = 15 ,
IMG_THREE = 16 } 

