PATH_POPUP_SWEEP_ONCE = "tui/tui_popup_sweep_once.xml"

Tag_popup_sweep_once = { 
PANEL_SWEEP_ONCE = 1 ,
IMG9_ONCE_BG3 = 2 ,
IMG9_BG2_ONCE = 3 ,
LAB_SWEEP_ONCE_TITLE = 4 ,
IMG_EXP_ONCE = 5 ,
IMG_ONCE_GOLD = 6 ,
LAB_SWEEP_ONCE_EXP = 7 ,
LAB_SWEEP_ONCE_GOLD = 8 ,
LAYOUT_ONCE_ITEM1 = 9 ,
LAYOUT_ONCE_ITEM4 = 11 ,
LAYOUT_ONCE_ITEM3 = 13 ,
LAYOUT_ONCE_ITEM2 = 15 ,
BTN_ONCE_SURE = 17 ,
LAB_ONCE_SURE = 18 ,
IMG9_SWEEP_BG_ONE = 19 ,
LAB_ITEM_NUM4 = 20 ,
LAB_ITEM_NUM3 = 21 ,
LAB_ITEM_NUM2 = 22 ,
LAB_ITEM_NUM1 = 23 } 

