PATH_POPUP_PVP_DEFEAT = "tui/tui_popup_pvp_defeat.xml"

Tag_popup_pvp_defeat = { 
PANEL_PVP_DEFEAT = 1 ,
IMG9_POPUP_CONTENT_DEFEAT = 2 ,
LAYOUT_TRAIN = 3 ,
BTN_TRAIN = 4 ,
LAYOUT_PET_TRAIN = 5 ,
IMG_TRAIN = 7 ,
LAYOUT_SKILL = 8 ,
BTN_SKILL = 9 ,
LAYOUT_PET_SKILL = 10 ,
IMG_SKILL = 12 ,
IMG_WOOD_TOP1 = 13 ,
IMG_WOOD_TOP2 = 14 ,
IMG_WOOD_BOTTOM1 = 15 ,
IMG_WOOD_BOTTOM2 = 16 ,
LAB_DEFEAT_TIPS = 17 ,
IMG9_POPUP_DEFEAT_BG = 18 ,
LAYOUT_LOSE = 19 ,
BTN_CLOSE = 21 ,
LAB_CLOSE = 22 } 

