PATH_UI_DEFENSE_TEAM = "tui/tui_ui_defense_team.xml"

Tag_ui_defense_team = { 
PANEL_DEFENSE_TEAM = 1 ,
LAYOUT_BG = 3 ,
IMG_CIRCLE_3 = 5 ,
IMG_CIRCLE_2 = 6 ,
IMG_CIRCLE_1 = 7 ,
IMG_CIRCLE_4 = 8 ,
IMG_CIRCLE_5 = 9 ,
IMG_CIRCLE_6 = 10 ,
LAYOUT_BATTLE = 11 ,
LAYOUT_DEFENSE = 14 ,
IMG9_POPUP_BG_BG = 15 ,
IMG_MATRIX_FRAME1 = 16 ,
IMG_MATRIX_FRAME2 = 17 ,
LAB_XUANZE = 18 ,
GV_DEFENSETEAM = 19 ,
BTN_BACK = 20 ,
BTN_SAVE = 21 ,
LAB_TEAM_RETURNLAB_TEAM_RETURN = 22 ,
LAB_SAVE_TEAM = 23 ,
BTN_LAST_LEFT = 24 ,
BTN_NEXT_RIGHT = 25 } 

