PATH_POPUP_SELECTSERVICER = "tui/tui_popup_selectservicer.xml"

Tag_popup_selectservicer = { 
PANEL_POPUP_SELECTSERVICER = 1 ,
IMG_DECORATE3 = 2 ,
IMG_SERVER_BG = 3 ,
IMG_PIKAQIU3 = 4 ,
LAB_ZUIJIN = 5 ,
BTN_SERVER1 = 6 ,
LAB_SERVICER_NUM = 7 ,
LAB_QU = 8 ,
LAB_SERVICER = 9 ,
LAB_ALL = 10 ,
LIST_SERVER = 11 ,
IMG_CONTENT = 13 ,
CELL_SERVER = 14 ,
BTN_SERVER2 = 15 ,
LAB_SERVERTH = 16 ,
LAB_SERVERQU = 17 ,
LAB_SERVER_NAME = 18 } 

