PATH_POPUP_MAIL = "tui/tui_popup_mail.xml"

Tag_popup_mail = { 
PANEL_POPUP_MAIL = 1 ,
IMG9_MAIL_BG_1 = 2 ,
IMG_WOOD_TOP1 = 4 ,
LIST_MAIL = 5 ,
LAYOUT_MAIL_X = 7 ,
IMG9_POPUP = 9 ,
IMG_TITLE_MAIL1 = 10 ,
IMG_TITLE_MAIL2 = 11 ,
BTN_CLOSE = 12 ,
IMG_MAIL_TITLE = 13 ,
CELL_MAIL = 14 ,
LAYOUT_MAIL_CELL = 15 ,
IMG_MAIL_CELL_BG = 16 ,
LAYOUT_ITEM_IMG = 17 ,
LAB_MAIL_TITLE = 19 ,
LAB_MAIL_DATE = 20 ,
IMG_ITEM_FRAME = 21 } 

