PATH_POPUP_LOGIN = "tui/tui_popup_login.xml"

Tag_popup_login = { 
PANEL_POPUP_LOGIN = 1 ,
IMG_DECORATE1 = 2 ,
IMG_POPUP_1 = 3 ,
LAB_ACCOUNT = 4 ,
LAB_PASSWORD = 5 ,
EDIT_ACCOUNT = 6 ,
EDIT_PASSWORD = 7 ,
BTN_REGISTER = 8 ,
LAB_REGISTION = 9 ,
BTN_SURE_LOGIN = 10 ,
LAB_LOGIN2 = 11 ,
IMG_PIKAQIU1 = 12 } 

