PATH_POPUP_GOLDHAND_ENSURE = "tui/tui_popup_goldhand_ensure.xml"

Tag_popup_goldhand_ensure = { 
PANEL_ENSURE = 1 ,
IMG9_POPUP_BG3 = 2 ,
IMG9_POPUP_BG2 = 3 ,
IMG9_POPUP2 = 4 ,
LAB_ENSURE_1 = 15 ,
LAB_ENSURE_DIAMONDNUM = 6 ,
LAB_ENSURE_2 = 7 ,
LAB_ENSURE_TIMES = 8 ,
LAB_ENSURE_3 = 9 ,
IMG_DIAMIND_SECOND = 10 ,
BTN_EDIT = 11 ,
BTN_ENSURE = 12 ,
LAB_ENSURE = 13 ,
LAB_EDIT = 14 } 

