PATH_POPUP_MAIL_READ = "tui/tui_popup_mail_read.xml"

Tag_popup_mail_read = { 
PANEL_POPUP_READ = 1 ,
IMG_MAIL_BG = 2 ,
LIST_READ = 3 ,
LAYOUT_CONTENT_SHOW = 5 ,
IMG9_MAILCONTENT_BG = 6 ,
LAB_GOLD = 7 ,
LAB_DIAMOND = 8 ,
GV_MAILITEM = 9 ,
IMG_GOLD = 10 ,
IMG_DIAMOND = 11 ,
IMG_SPLIT = 12 ,
LAB_MAIL = 13 ,
BTN_DRAW = 14 ,
BTN_GETCOMMON = 15 ,
LAB_GETMAIL = 16 ,
CELL_MAILITEM = 17 ,
LAYOUT_MAILPET_1 = 18 } 

