PATH_POPUP_DAILYATTENDANCE = "tui/tui_popup_dailyattendance.xml"

Tag_popup_dailyattendance = { 
PANEL_POPUP_DAILYATTENDANCE = 1 ,
IMG9_GRAY_REGISTRATION = 2 ,
IMG9_POPUP_BG = 3 ,
IMG9_POPUP = 4 ,
IMG_POPUP_TITLE = 5 ,
LAB_REGISTRATION_3 = 6 ,
LAB_REGISTRATION_NUM = 7 ,
LAB_REGISTRATION_5 = 8 ,
LAB_REGISTRATION_2 = 9 ,
GV_REGISTRATION = 10 ,
BTN_CLOSE = 11 ,
CELL_REGISTRATION = 12 ,
IMG_REGISTRATION_RECT = 13 ,
IMG_REGISTRATION_PROP = 14 ,
IMG_VIPDOUBLE = 15 ,
IMG_THREE = 16 ,
IMG_SELECT = 17 } 

