PATH_POPUP_ACTIVITY1_TURNTABLE = "tui/tui_popup_activity1_turntable.xml"

Tag_popup_activity1_turntable = { 
PANEL_POPUP_ACTIVITY1_TURNTABLE = 1 ,
LAYOUT_TURNTABLE = 2 ,
IMG_TURNTABLE = 3 ,
IMG_BAG_ICON1 = 4 ,
IMG_BAG_ICON3 = 5 ,
IMG_NORMAL_BALL_2 = 6 ,
IMG_NORMAL_BALL_3 = 7 ,
IMG_DIAMOND_SHOW1 = 8 ,
IMG_DIAMOND_SHOW2 = 9 ,
IMG_GOLD_SHOW1 = 10 ,
IMG_GOLD_SHOW2 = 11 ,
BTN_START = 12 } 

