PATH_UI_ACTIVITY = "tui/tui_ui_activity.xml"

Tag_ui_activity = { 
PANEL_ACTIVITY = 1 ,
LAYOUT_TOP = 3 ,
IMG9_POPUP_BG = 4 ,
IMG_WOOD_ACTIVITY_BG2 = 5 ,
IMG_WOOD_ACTIVITY_BG1 = 6 ,
IMG_BG2 = 7 ,
IMG_BG1 = 8 ,
IMG_POPUP_TITLE1 = 10 ,
IMG_ACTIVITY_TITLE = 11 ,
LIST_ACTIVITY = 12 ,
LAYOUT_ACTIVITY = 14 ,
BTN_DAILYSIGN = 15 ,
LAYOUT_BOTTOM = 16 ,
IMG_BOTTOM_BG = 17 ,
BTN_CLOSE = 18 ,
LAB_RETURN = 19 } 

